parameters:
#    jro_burn.example.class: JRO\Bundle\BurnBundle\Example

services:
#    jro_burn.example:
#        class: %jro_burn.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
